// static-web-app/examples/react-static-web-app/src/App.tsx
import { useState } from "react";

import "./App.css";

function App() {
  const [results, setResults] = useState("[]");

  //develpment
  //const apiUrl: string = "http://localhost:5000/api";
  //production app service not linked to static web app
  //const apiUrl: string = 'https://lcs16-swa-as.azurewebsites.net/api';
  //production app service linked to static web app
  const apiUrl: string = "/api";

  const getApi = async () => {
    const endpointUrl = `${apiUrl}/weatherforecast`;
    console.log(endpointUrl);
    const response = await fetch(endpointUrl);
    const data = await response.json();
    setResults(JSON.stringify(data, null, 4));
  };

  return (
    <div className="content" role="main">
      <svg width="100" height="100" xmlns="http://www.w3.org/2000/svg" viewBox="-11.5 -10.23174 23 20.46348">
        <title>React Logo</title>
        <circle cx="0" cy="0" r="2.05" fill="#61dafb" />
        <g stroke="#61dafb" strokeWidth="1" fill="none">
          <ellipse rx="11" ry="4.2" />
          <ellipse rx="11" ry="4.2" transform="rotate(60)" />
          <ellipse rx="11" ry="4.2" transform="rotate(120)" />
        </g>
      </svg>
      <h1>react-static-web-app</h1>
      <p>Test Application</p>
      <br />
      <button onClick={getApi} className="btn btn-primary">
        Get Api
      </button>
      <br />
      <pre>{results}</pre>
    </div>
  );
}

export default App;

// static-web-app/examples/angular-static-web-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, HttpClientModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'angular-static-web-app';

  //develpment
  //private apiUrl: string = 'http://localhost:5000/api';
  //production app service not linked to static web app
  //private apiUrl: string = 'https://lcs16-swa-as.azurewebsites.net/api';
  //production app service linked to static web app
  private apiUrl: string = '/api';

  public results: any[] = [];

  constructor(private http: HttpClient) {}

  getApi() {
    let endpointUrl = `${this.apiUrl}/weatherforecast`;

    this.http.get<any>(endpointUrl).subscribe((resp) => {
      console.log(endpointUrl);
      this.results = resp;
    });
  }
}

<div class="content" role="main">
  <svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    viewBox="0 0 250 250"
    style="enable-background: new 0 0 250 250"
    xml:space="preserve"
    width="100"
    height="100"
  >
    <style type="text/css">
      .st0 {
        fill: #dd0031;
      }
      .st1 {
        fill: #c3002f;
      }
      .st2 {
        fill: #ffffff;
      }
    </style>
    <g>
      <polygon
        class="st0"
        points="125,30 125,30 125,30 31.9,63.2 46.1,186.3 125,230 125,230 125,230 203.9,186.3 218.1,63.2 	"
      />
      <polygon
        class="st1"
        points="125,30 125,52.2 125,52.1 125,153.4 125,153.4 125,230 125,230 203.9,186.3 218.1,63.2 125,30 	"
      />
      <path
        class="st2"
        d="M125,52.1L66.8,182.6h0h21.7h0l11.7-29.2h49.4l11.7,29.2h0h21.7h0L125,52.1L125,52.1L125,52.1L125,52.1
		L125,52.1z M142,135.4H108l17-40.9L142,135.4z"
      />
    </g>
  </svg>
  <h1>angular-static-web-app</h1>
  <p>Test Application</p>
  <br />
  <button (click)="getApi()" class="btn btn-primary">Get Api</button>
  <br />
  <pre>{{ results | json }}</pre>
</div>
